CREATE TABLE IF NOT EXISTS `base_enterprise_verify_config` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `school_id` int unsigned NOT NULL COMMENT 'school root department id',
  `verify_type_id` int unsigned DEFAULT NULL COMMENT 'verify type id',
  `verify_first_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'first verify role id',
  `verify_second_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'second verify role id',
  `verify_third_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'third verify role id',
  `verify_fourth_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'fourth verify role id',
  `verify_fifth_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'fifth verify role id',
  `remarks` varchar(1000) DEFAULT NULL COMMENT 'config remarks',
  `version` int DEFAULT '0' COMMENT 'optimistic lock version',
  PRIMARY KEY (`id`),
  KEY `idx_base_enterprise_verify_config_school` (`school_id`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='enterprise info verify config';

CREATE TABLE IF NOT EXISTS `main_enterprise_info` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `company_id` int unsigned NOT NULL COMMENT 'company department id',
  `school_id` int unsigned NOT NULL COMMENT 'school root department id',
  `admin_user_id` int unsigned NOT NULL COMMENT 'company admin user id',
  `code` varchar(50) DEFAULT NULL COMMENT 'unified social credit code snapshot',
  `name` varchar(200) DEFAULT NULL COMMENT 'company name snapshot',
  `contact_name` varchar(100) DEFAULT NULL COMMENT 'contact person',
  `contact_phone` varchar(50) DEFAULT NULL COMMENT 'contact phone',
  `contact_email` varchar(100) DEFAULT NULL COMMENT 'contact email',
  `address` varchar(255) DEFAULT NULL COMMENT 'company address',
  `legal_person` varchar(100) DEFAULT NULL COMMENT 'legal person',
  `industry` varchar(100) DEFAULT NULL COMMENT 'industry',
  `company_scale` varchar(100) DEFAULT NULL COMMENT 'company scale',
  `business_scope` varchar(1000) DEFAULT NULL COMMENT 'business scope',
  `introduction` varchar(2000) DEFAULT NULL COMMENT 'company introduction',
  `remarks` varchar(1000) DEFAULT NULL COMMENT 'remarks or audit note',
  `verify_type_id` int unsigned DEFAULT NULL COMMENT 'verify type id',
  `verify_first_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'first verify role id',
  `verify_second_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'second verify role id',
  `verify_third_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'third verify role id',
  `verify_fourth_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'fourth verify role id',
  `verify_fifth_role_id` int unsigned NOT NULL DEFAULT '0' COMMENT 'fifth verify role id',
  `audit_status` tinyint NOT NULL DEFAULT '-1' COMMENT '-1 draft, 0 pending, 1 approved, 2 rejected, 3 returned',
  `current_verify_type_id` int DEFAULT '1' COMMENT 'current verify level',
  `is_current` bit(1) NOT NULL DEFAULT b'0' COMMENT 'whether this version is current approved version',
  `version_no` int unsigned NOT NULL DEFAULT '1' COMMENT 'version number inside same company',
  `approved_time` datetime DEFAULT NULL COMMENT 'approved time',
  `approved_by` int unsigned DEFAULT NULL COMMENT 'final approver user id',
  `version` int DEFAULT '0' COMMENT 'optimistic lock version',
  PRIMARY KEY (`id`),
  KEY `idx_main_enterprise_info_company` (`company_id`, `is_deleted`),
  KEY `idx_main_enterprise_info_school_status` (`school_id`, `audit_status`, `is_deleted`),
  KEY `idx_main_enterprise_info_current` (`company_id`, `is_current`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='enterprise info declaration and audit';
